<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>dotnet_vsa_template</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\Configuration\**" />
    <Content Remove="Common\Configuration\**" />
    <EmbeddedResource Remove="Common\Configuration\**" />
    <None Remove="Common\Configuration\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="9.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

</Project>
